# Generated by Django 6.0.3 on 2026-03-12 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_page_sections(apps, schema_editor):
    PageSection = apps.get_model('accounts', 'PageSection')
    PageSectionCard = apps.get_model('accounts', 'PageSectionCard')

    seeded_sections = [
        {
            'page': 'home',
            'slot': 'home_signals',
            'audience': 'all',
            'eyebrow': 'Live metrics',
            'title': 'Homepage signal cards',
            'description': 'Controls the live metric cards on the public homepage.',
            'display_order': 1,
            'cards': [
                {
                    'card_key': 'launch_requests',
                    'eyebrow': 'Public launch',
                    'tone': 'sea',
                    'display_order': 1,
                },
                {
                    'card_key': 'media_sync',
                    'eyebrow': 'Media sync',
                    'tone': 'foam',
                    'display_order': 2,
                },
                {
                    'card_key': 'field_telemetry',
                    'eyebrow': 'Field telemetry',
                    'tone': 'sun',
                    'display_order': 3,
                },
            ],
        },
        {
            'page': 'home',
            'slot': 'guest_access',
            'audience': 'guest',
            'eyebrow': 'Guest access',
            'title': 'Guest sidebar cards',
            'description': 'Controls the guest-facing access cards on the homepage sidebar.',
            'display_order': 2,
            'cards': [
                {
                    'card_key': 'public_pages',
                    'eyebrow': 'Public pages',
                    'tone': 'sea',
                    'display_order': 1,
                },
                {
                    'card_key': 'operations',
                    'eyebrow': 'Operations',
                    'tone': 'sand',
                    'display_order': 2,
                },
                {
                    'card_key': 'publishing',
                    'eyebrow': 'Publishing',
                    'tone': 'foam',
                    'display_order': 3,
                },
            ],
        },
    ]

    for section_defaults in seeded_sections:
        cards = section_defaults.pop('cards')
        page_section, _ = PageSection.objects.update_or_create(
            page=section_defaults['page'],
            slot=section_defaults['slot'],
            audience=section_defaults['audience'],
            defaults=section_defaults,
        )

        for card_defaults in cards:
            PageSectionCard.objects.update_or_create(
                section=page_section,
                card_key=card_defaults['card_key'],
                defaults=card_defaults,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_product_announcement_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leakreport',
            name='observed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='admin_note_description',
            field=models.TextField(default='The seeded admin account exists in Django, but the frontend does not display any password. Admins can create other system administrators, register sensors, publish products, add team members, and review contact messages after sign-in.'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='workspace_description_admin',
            field=models.TextField(default='You are signed in as an admin. The launch dashboard is live, the About Us page is powered by Django, and you can manage system administrators, sensors, team members, products, and contact messages from this workspace.'),
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('products', 'Products'), ('workspace', 'Workspace')], max_length=24)),
                ('slot', models.SlugField(max_length=64)),
                ('audience', models.CharField(choices=[('all', 'All visitors'), ('guest', 'Guests'), ('user', 'Signed-in users'), ('admin', 'Admins')], default='all', max_length=24)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_link', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['page', 'display_order', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('page', 'slot', 'audience'), name='unique_page_section_slot_audience')],
            },
        ),
        migrations.CreateModel(
            name='PageSectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.SlugField(max_length=80)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('tone', models.CharField(blank=True, choices=[('sea', 'Sea'), ('foam', 'Foam'), ('sun', 'Sun'), ('sand', 'Sand'), ('neutral', 'Neutral')], max_length=24)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.pagesection')),
            ],
            options={
                'ordering': ['section', 'display_order', 'card_key'],
                'constraints': [models.UniqueConstraint(fields=('section', 'card_key'), name='unique_page_section_card_key')],
            },
        ),
        migrations.RunPython(seed_page_sections, migrations.RunPython.noop),
    ]
