# Generated by Django 6.0.3 on 2026-03-12 12:08

from django.db import migrations, models


def seed_dynamic_page_sections(apps, schema_editor):
    PageSection = apps.get_model('accounts', 'PageSection')
    PageSectionCard = apps.get_model('accounts', 'PageSectionCard')

    section_defaults = [
        {
            'page': 'workspace',
            'slot': 'visitor_cards',
            'audience': 'admin',
            'section_kind': 'cards',
            'eyebrow': 'Admin context',
            'title': 'Admin workspace cards',
            'description': 'Controls the workspace summary cards shown to administrators.',
            'display_order': 1,
            'cards': [
                {'card_key': 'inbox', 'eyebrow': 'Inbox', 'tone': 'sun', 'display_order': 1},
                {'card_key': 'publishing_gaps', 'eyebrow': 'Publishing gaps', 'tone': 'foam', 'display_order': 2},
                {'card_key': 'operations', 'eyebrow': 'Operations', 'tone': 'sea', 'display_order': 3},
                {'card_key': 'demand', 'eyebrow': 'Demand', 'tone': 'sand', 'display_order': 4},
            ],
        },
        {
            'page': 'workspace',
            'slot': 'visitor_cards',
            'audience': 'user',
            'section_kind': 'cards',
            'eyebrow': 'User context',
            'title': 'User workspace cards',
            'description': 'Controls the workspace summary cards shown to signed-in users.',
            'display_order': 2,
            'cards': [
                {'card_key': 'field_view', 'eyebrow': 'Field view', 'tone': 'sea', 'display_order': 1},
                {'card_key': 'public_site', 'eyebrow': 'Public site', 'tone': 'foam', 'display_order': 2},
                {'card_key': 'demand', 'eyebrow': 'Demand', 'tone': 'sand', 'display_order': 3},
            ],
        },
        {
            'page': 'home',
            'slot': 'home_desk_operations',
            'audience': 'all',
            'section_kind': 'feed',
            'source_type': 'leak_reports',
            'tab_label': 'Operations',
            'eyebrow': 'Field desk',
            'title': 'Leak telemetry and sensor movement',
            'description': '',
            'item_limit': 5,
            'display_order': 3,
        },
        {
            'page': 'home',
            'slot': 'home_desk_notices',
            'audience': 'all',
            'section_kind': 'feed',
            'source_type': 'announcements',
            'tab_label': 'Notices',
            'eyebrow': 'Public desk',
            'title': 'Announcements and visitor-facing notices',
            'description': '',
            'item_limit': 5,
            'display_order': 4,
        },
        {
            'page': 'home',
            'slot': 'home_desk_products',
            'audience': 'all',
            'section_kind': 'feed',
            'source_type': 'products',
            'tab_label': 'Products',
            'eyebrow': 'Catalog desk',
            'title': 'Published product media and product summaries',
            'description': '',
            'item_limit': 5,
            'display_order': 5,
        },
        {
            'page': 'home',
            'slot': 'home_desk_team',
            'audience': 'all',
            'section_kind': 'feed',
            'source_type': 'team_members',
            'tab_label': 'Team',
            'eyebrow': 'People desk',
            'title': 'About roster and visible team updates',
            'description': '',
            'item_limit': 5,
            'display_order': 6,
        },
    ]

    for defaults in section_defaults:
        cards = defaults.pop('cards', [])
        section, _ = PageSection.objects.update_or_create(
            page=defaults['page'],
            slot=defaults['slot'],
            audience=defaults['audience'],
            defaults=defaults,
        )

        for card_defaults in cards:
            PageSectionCard.objects.update_or_create(
                section=section,
                card_key=card_defaults['card_key'],
                defaults=card_defaults,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_leakreport_observed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='item_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='section_kind',
            field=models.CharField(choices=[('cards', 'Cards'), ('feed', 'Feed')], default='cards', max_length=24),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='source_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('leak_reports', 'Leak reports'), ('announcements', 'Announcements'), ('products', 'Products'), ('team_members', 'Team members')], max_length=40),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='tab_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(seed_dynamic_page_sections, migrations.RunPython.noop),
    ]
