# Generated by Django 6.0.3 on 2026-03-12 12:24

from django.db import migrations


def seed_additional_dynamic_sections(apps, schema_editor):
    PageSection = apps.get_model('accounts', 'PageSection')
    PageSectionCard = apps.get_model('accounts', 'PageSectionCard')

    section_defaults = [
        {
            'page': 'about',
            'slot': 'about_signals',
            'audience': 'all',
            'section_kind': 'cards',
            'eyebrow': 'Live structure',
            'title': 'How the About page stays dynamic',
            'description': 'Controls the About page signal cards.',
            'display_order': 1,
            'cards': [
                {'card_key': 'roster', 'eyebrow': 'Roster', 'tone': 'sea', 'display_order': 1},
                {'card_key': 'portraits', 'eyebrow': 'Portraits', 'tone': 'foam', 'display_order': 2},
                {'card_key': 'contact_intake', 'eyebrow': 'Contact intake', 'tone': 'sun', 'display_order': 3},
            ],
        },
        {
            'page': 'about',
            'slot': 'about_workflow',
            'audience': 'all',
            'section_kind': 'cards',
            'eyebrow': 'About workflow',
            'title': 'How the About page stays dynamic',
            'description': 'Controls the About page checklist content.',
            'display_order': 2,
            'cards': [
                {'card_key': 'team_records', 'display_order': 1},
                {'card_key': 'portrait_replacement', 'display_order': 2},
                {'card_key': 'shared_backend', 'display_order': 3},
            ],
        },
        {
            'page': 'products',
            'slot': 'product_signals',
            'audience': 'all',
            'section_kind': 'cards',
            'eyebrow': 'Platform network',
            'title': 'How the catalog connects to live operations',
            'description': 'Controls the product page signal cards.',
            'display_order': 1,
            'cards': [
                {'card_key': 'catalog', 'eyebrow': 'Catalog', 'tone': 'sea', 'display_order': 1},
                {'card_key': 'public_reach', 'eyebrow': 'Public reach', 'tone': 'foam', 'display_order': 2},
                {'card_key': 'operations_link', 'eyebrow': 'Operations link', 'tone': 'sun', 'display_order': 3},
            ],
        },
        {
            'page': 'products',
            'slot': 'product_journey',
            'audience': 'all',
            'section_kind': 'cards',
            'eyebrow': 'Publishing loop',
            'title': 'What changes when new data arrives',
            'description': 'Controls the product page checklist content.',
            'display_order': 2,
            'cards': [
                {'card_key': 'media_ready', 'display_order': 1},
                {'card_key': 'team_support', 'display_order': 2},
                {'card_key': 'launch_requests', 'display_order': 3},
                {'card_key': 'outward_update', 'display_order': 4},
            ],
        },
    ]

    for defaults in section_defaults:
        cards = defaults.pop('cards', [])
        section, _ = PageSection.objects.update_or_create(
            page=defaults['page'],
            slot=defaults['slot'],
            audience=defaults['audience'],
            defaults=defaults,
        )

        for card_defaults in cards:
            PageSectionCard.objects.update_or_create(
                section=section,
                card_key=card_defaults['card_key'],
                defaults=card_defaults,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_pagesection_item_limit_pagesection_section_kind_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_additional_dynamic_sections, migrations.RunPython.noop),
    ]
