# Generated by Django 6.0.3 on 2026-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_sitecontent_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='login_background_primary',
            field=models.FileField(blank=True, upload_to='site_content/login/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='login_background_secondary',
            field=models.FileField(blank=True, upload_to='site_content/login/'),
        ),
    ]
