# Generated by Django 6.0.3 on 2026-03-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_sitecontent_login_background_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='login_background_video',
            field=models.FileField(blank=True, upload_to='site_content/login/'),
        ),
    ]
