# Generated by Django 6.0.3 on 2026-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_sitecontent_login_background_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='workspace_background_primary',
            field=models.FileField(blank=True, upload_to='site_content/workspace/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='workspace_background_secondary',
            field=models.FileField(blank=True, upload_to='site_content/workspace/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='workspace_background_video',
            field=models.FileField(blank=True, upload_to='site_content/workspace/'),
        ),
    ]
